# Generated by Django 4.1.4 on 2022-12-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва принтера')),
                ('api_key', models.CharField(max_length=250, unique=True, verbose_name='Ключ доступу до API')),
                ('check_type', models.CharField(max_length=50, verbose_name='Тип чека який друкує принтер')),
                ('point_id', models.IntegerField(verbose_name="Точка до якої прив'язаний принтер")),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтери',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_type', models.CharField(max_length=50, verbose_name='Тип чеку')),
                ('order', models.JSONField(verbose_name='Інформація про замовлення')),
                ('status', models.CharField(max_length=50, verbose_name='Статус чеку')),
                ('pdf_file', models.FileField(blank=True, max_length=5000, null=True, upload_to='', verbose_name='PDF-файл')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
